CREATE VIEW VerInstituicoes
AS
SELECT ID,NOME_FANTASIA AS 'NOME',CNPJ,LOGRADOURO,CEP,UF,CIDADE FROM INSTITUICOES;
GO

CREATE VIEW VerEventos
AS
SELECT EV.ID,EV.NOME AS 'EVENTO' ,EV.DESCRICAO,TE.ID AS 'ID_TIPO_EVENTO', TE.NOME AS 'TIPO_EVENTO' ,EV.DATA_EVENTO , EV.ACESSO_LIVRE , INS.ID AS 'ID_INSTITUICAO' ,INS.NOME AS 'INSTITUICAO'
FROM EVENTOS AS EV
LEFT JOIN VerInstituicoes AS INS ON INS.ID = EV.ID_INSTITUICAO
LEFT JOIN TIPO_EVENTO AS TE ON TE.ID = EV.ID_TIPO_EVENTO ;
GO

CREATE VIEW VerUsuarios
AS 
SELECT US.ID,US.NOME AS 'NOME' , US.EMAIL ,TI.NOME AS 'TIPO_USUARIO'
FROM USUARIOS AS US 
LEFT JOIN TIPO_USUARIO AS TI ON US.ID_TIPO_USUARIO = TI.ID;
GO

CREATE VIEW VerConvites 
AS
SELECT CONV.ID AS 'ID', US.ID AS 'ID_CONVIDADO' ,US.NOME AS 'CONVIDADO',  EV.ID AS 'ID_EVENTO' ,EV.NOME AS 'EVENTO' , TE.NOME AS 'TIPO_EVENTO',EV.DESCRICAO , INS.LOGRADOURO AS 'LOCAL',EV.DATA_EVENTO , CONV.SITUACAO
FROM CONVITES AS CONV
INNER JOIN USUARIOS AS US ON US.ID = CONV.ID_USUARIO
INNER JOIN EVENTOS AS EV ON EV.ID = CONV.ID_EVENTO
INNER JOIN INSTITUICOES AS INS ON INS.ID = EV.ID_INSTITUICAO
INNER JOIN TIPO_EVENTO AS TE ON TE.ID = EV.ID_TIPO_EVENTO;
GO